# Generated by Django 5.1.3 on 2024-11-25 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                (
                    "portfolio_name",
                    models.CharField(
                        max_length=100, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("portfolio_code", models.CharField(max_length=100, unique=True)),
                ("school_number", models.CharField(max_length=100, unique=True)),
                ("full_name", models.CharField(max_length=100)),
                ("portfolio_type", models.CharField(max_length=100)),
                ("status", models.CharField(max_length=100)),
                ("type_of_emp", models.CharField(max_length=100)),
                ("father_name", models.CharField(max_length=100)),
                ("mother_name", models.CharField(max_length=100)),
                ("cusp", models.CharField(max_length=100)),
                ("entered_by", models.CharField(max_length=100)),
                ("confirmed", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("asset_name", models.CharField(max_length=100)),
                ("quantity", models.FloatField()),
                ("price", models.FloatField()),
                (
                    "portfolio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="assets.portfolio",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="POS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pos_date", models.DateField()),
                ("pos_amount", models.FloatField()),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="assets.transaction",
                    ),
                ),
            ],
        ),
    ]
